app:
  telegram:
    bot-token: "${BOT_TOKEN}"
    target-channel-id: "${TARGET_CHANNEL_ID}"

  monitor:
    duplicate-ttl-minutes: 5
    context-ttl: 15m

    location-categories:
      - category: "біла церква"
        aliases:
          - "біла церква"
          - "білу церкву"
          - "білій церкві"
          - "білою церквою"
          - "білої церкви"
          - "бц"
          - "біла"
          - "білу"
          - "білій"
          - "білою"
          - "білої"
          - "білоцерківський район"
          - "білоцерківський"
          - "білоцерківщини"
          - "білоцерківського"
          - "білоцерківському"
          - "білоцерківську"
          - "білоцерківській"
          - "білоцерківщина"
          - "білоцерківщині"
          - "білоцерківської"

      - category: "васильків"
        aliases:
          - "васильків"
          - "василькова"
          - "василькову"
          - "василькові"
          - "васильковом"
          - "васильківська"
          - "васильківського"
          - "васильківської"

      - category: "володарка"
        aliases:
          - "володарка"
          - "володарку"
          - "володарській"
          - "володарки"
          - "володарці"
          - "володаркою"


      - category: "вільна тарасівка"
        aliases:
          - "вільна тарасівка"
          - "вільної тарасівки"
          - "вільну тарасівку"
          - "вільній тарасівці"
          - "вільною тарасівкою"
          - "тарасівка"
          - "тарасівку"

      - category: "мала вільшанка"
        aliases:
          - "мала вільшанка"
          - "малої вільшанки"
          - "малу вільшанку"
          - "малій вільшанці"
          - "малою вільшанкою"
          - "вільшанки"
          - "вільшани"
          - "вільшана"
          - "вільшанка"
          - "вільшанок"

      - category: "гребінки"
        aliases:
          - "гребінки"
          - "гребінок"
          - "гребінках"

      - category: "глушки"
        aliases:
          - "глушки"
          - "глушках"
          - "глушками"

      - category: "гайок"
        aliases:
          - "гайка"
          - "гайок"
          - "гайках"

      - category: "гай"
        aliases:
          - "гай"

      - category: "дрозди"
        aliases:
          - "дрозди"
          - "дроздів"
          - "дроздах"
          - "дроздами"

      - category: "дослідницьке"
        aliases:
          - "дослідницьке"
          - "дослідницьким"
          - "дослідницького"

      - category: "заріччя"
        aliases:
          - "заріччя"
          - "заріччям"

      - category: "леван"
        aliases:
          - "леван"
          - "ліван"
          - "леваневського"

      - category: "мазепинці"
        aliases:
          - "мазепинці"
          - "мазепинців"
          - "мазепинцях"
          - "мазепинцями"

      - category: "обухів"
        aliases:
          - "обухів"
          - "обухова"
          - "обухову"
          - "обухові"
          - "обуховом"
          - "обухівський"
          - "обухівська"
          - "обухівського"
          - "обухівської"
          - "обухівську"
          - "обухівські"
          - "обухівській"

      - category: "острійки"
        aliases:
          - "острійки"
          - "острійків"
          - "острійках"
          - "острійками"

      - category: "олійникова слобода"
        aliases:
          - "олійникова слобода"
          - "олійникової слободи"
          - "олійникову слободу"
          - "олійниковій слободі"
          - "олійниковою слободою"
          - "олійник"
          - "олійником"
          - "олійникова"
          - "олійника"
          - "слобода"

      - category: "пилипча"
        aliases:
          - "пилипча"
          - "пилипче"
          - "пилипчі"
          - "пилипчею"

      - category: "піщана"
        aliases:
          - "піщана"
          - "піщаної"
          - "піщану"
          - "піщаній"
          - "піщаною"
          - "піщаний"

      - category: "пологи"
        aliases:
          - "пологи"
          - "пологами"
          - "пологів"

      - category: "пугачівка"
        aliases:
          - "пугачівка"
          - "пугачівкою"
          - "пугачівки"

      - category: "пінчуки"
        aliases:
          - "пінчуки"
          - "пінчуками"
          - "пінчуків"

      - category: "рокитне"
        aliases:
          - "рокитне"
          - "рокитного"
          - "рокитному"
          - "рокитним"

      - category: "росава"
        aliases:
          - "росава"
          - "росавою"
          - "росави"

      - category: "сквира"
        aliases:
          - "сквира"
          - "сквири"
          - "сквиру"
          - "сквирі"
          - "сквирою"
          - "сквирська"
          - "сквирського"

      - category: "стави"
        aliases:
          - "стави"

      - category: "семенівка"
        aliases:
          - "семенівка"
          - "семенівку"
          - "семенівки"

      - category: "салиха"
        aliases:
          - "салиха"
          - "салихи"
          - "салихою"

      - category: "скребиші"
        aliases:
          - "скребиші"
          - "скребишами"
          - "скребишів"

      - category: "сеньківка"
        aliases:
          - "сеньківку"
          - "сеньківка"
          - "сеньківкою"

      - category: "сорокотяги"
        aliases:
          - "сорокотяги"
          - "сорокотягами"

      - category: "сидори"
        aliases:
          - "сидори"
          - "сидорами"
          - "сидорів"

      - category: "сухоліси"
        aliases:
          - "сухоліси"
          - "сухолісів"
          - "сухолісах"
          - "сухолісами"

      - category: "терезине"
        aliases:
          - "терезине"
          - "терезиного"
          - "терезиному"

      - category: "тараща"
        aliases:
          - "тараща"
          - "таращі"
          - "таращу"
          - "таращою"

      - category: "таращанський"
        aliases:
          - "таращанський"

      - category: "томилівка"
        aliases:
          - "томилівка"
          - "томилівки"
          - "томилівку"
          - "томилівці"
          - "томилівкою"

      - category: "трушки"
        aliases:
          - "трушки"
          - "трушок"
          - "трушках"
          - "трушками"

      - category: "узин"
        aliases:
          - "узин"
          - "узина"
          - "узину"
          - "узині"
          - "узином"

      - category: "фурси"
        aliases:
          - "фурси"
          - "фурсів"
          - "фурсах"
          - "фурсами"

      - category: "храпачі"
        aliases:
          - "храпачі"
          - "храпачів"
          - "храпачах"
          - "храпачами"

      - category: "шкарівка"
        aliases:
          - "шкарівка"
          - "шкарівки"
          - "шкарівку"
          - "шкарівці"
          - "шкарівкою"

      - category: "шаліївка"
        aliases:
          - "шаліївку"
          - "шаліївка"
          - "шаліївки"
          - "шаліївкою"

      - category: "шамраївка"
        aliases:
          - "шамраївка"
          - "шамраївки"
          - "шамраївкою"
          - "шамраївку"

      - category: "київщина"
        aliases:
          - "київщина"
          - "київщині"
          - "київщину"
          - "київщиною"
          - "київська область"
          - "київській області"
          - "київську область"

      - category: "уся україна"
        aliases:
          - "уся україна"
          - "вся україна"

    directions:
      - "на"
      - "до"
      - "курс на"
      - "курсом на"
      - "по курсу"
      - "повз"
      - "далі на"
      - "летить на"
      - "підлітає до"
      - "рухається на"
      - "прямує на"
      - "у напрямку"
      - "в напрямку"
      - "з"
      - "з боку"

    target-categories:
      - category: "бпла"
        aliases:
          - "бпла"
          - "безпілотник"
          - "безпілотних"
          - "безпілотників"
          - "безпілотники"
          - "безпілотникiв" # з латинською і
          - "безпілотниками"
          - "безпілотними"
          - "безпілотні"
          - "безпліотники" # друкарська помилка
          - "безпілотника"
          - "безпілотником"
          - "бандероль" # народна назва дрона
          - "бандеролі"
          - "бандеролей"
          - "бандеролям"
          - "бляшанка" # іронічна назва дрона
          - "бляшанки"
          - "дронами"
          - "дрон"
          - "дронам"
          - "дронових"
          - "дроновою"
          - "дронах"
          - "дронового"
          - "дронові"
          - "дроня"
          - "мопед" # народна назва Шахеда
          - "мопедах"
          - "ударних"
          - "ударні"
          - "ударними"
          - "ударний"
          - "шахед"
          - "шахеди"
          - "шахедів"
          - "шахедах"
          - "шахеду"
          - "шахеда"
          - "шахедами"
          - "шазедів" # друкарська помилка
          - "шахедіі" # друкарська помилка
          - "шазеди"   # друкарська помилка
          - "шахедам"
          - "табун" # народне позначення великої групи/зграї дронів
          - "далекобійних"
          - "дальні"
          - "дальніх"
          - "далекобійними"
          - "далекобійного"
          - "далекобійну"
          - "далекобійність"
          - "дальній"

      - category: "ракета"
        aliases:
          - "балістики"
          - "балістика"
          - "балістиці"
          - "балістичного"
          - "балістичних"
          - "балістику"
          - "балістичні"
          - "балістикою"
          - "балімтика" # друкарська помилка
          - "балістик"
          - "балістична"
          - "балістичне"
          - "балістичним"
          - "балістичною"
          - "балістичної"
          - "балітиска" # друкарська помилка
          - "міжконтинентальних"
          - "міжконтинентальною"
          - "орешнік" # балістична ракета середньої дальності РФ
          - "орєшнік"
          - "орешніка"
          - "орєшніками"
          - "орєшніки"
          - "орєшнікі"
          - "орєшніків"
          - "реактивний" # може стосуватися як реактивних КР/дронів, так і реактивної ППО/авіації
          - "реактивні"
          - "реактивних"
          - "реактивна"
          - "реактивного"
          - "реактивним"
          - "реактивними"
          - "ракети"
          - "ракет"
          - "ракета"
          - "ракетах"
          - "ракетами"
          - "ракетна"
          - "ракетної"
          - "ракетні"
          - "ракетою"
          - "ракету"
          - "ракетний"
          - "ракетно"
          - "ракетну"
          - "ракетною"
          - "ракетній"
          - "ракетобудуванні"
          - "швидкісна"
          - "швидкісним"
          - "швидкісні"

      - category: "міг"
        aliases:
          - "винищувачі"
          - "бомбардувальника"
          - "мігу" # винищувач МіГ-31К або МіГ-29
          - "міги"
          - "мігах"
          - "мігів"
          - "мігами"
          - "ракетоносії" # стратегічні літаки Ту-95/Ту-160 або кораблі
          - "ракетоносіїв"

    attention-words:
      - category: "службові слова"
        aliases:
          - "увагу"
          - "увага"
          - "уважно"
          - "увазі"
          - "уважні"
          - "уважними"
          - "загроза"
          - "загрози"
          - "загрозу"
          - "загрозі"

    message-intents:
      - intent: "COUNT_UPDATE"
        aliases:
          - "ще один"
          - "ще одна"
          - "ще"
          - "їх"
          - "тут вже"
          - "тут уже"
          - "штук"

      - intent: "ROUTE_UPDATE"
        aliases:
          - "розвернувся"
          - "повернув"
          - "звернув"
          - "йде"
          - "іде"
          - "летить"
          - "заходить"
          - "пішов"
          - "заходять"
          - "зайшов"
          - "зайшло"
          - "змінив"
          - "змінила"
          - "змінили"
          - "змінює"
          - "змінюють"
          - "завернув"
          - "завернула"
          - "завернули"
          - "завернуло"
          - "закрутився"
          - "закрутилося"

      - intent: "STATUS_UPDATE"
        aliases:
          - "не спостерігається"
          - "оновлення"
          - "збито"
          - "відбій"
          - "збиті"
          - "збили"
          - "збиває"
          - "знищено"
          - "знищили"
          - "знищений"
          - "знищенні"
          - "знищені"
          - "знищенню"
          - "знищується"
          - "зник"
          - "зникли"
          - "зникло"
          - "зникнення"
          - "здох"
          - "здохли"
          - "здохне"
          - "здохнути"
          - "зламався"
          - "зняли"
          - "зняти"
          - "знято"

      - intent: "LOCATION_UPDATE"
        aliases:
          - "на"
          - "до"
          - "від"
          - "з"
          - "біля"
          - "поблизу"
          - "над"

    sources:
      - chat-id: "-5519048152"
        title: "Тест джерело моніторингу"
        active: true

      - chat-id: "-5539045370"
        title: "Тест БЦ новини"
        active: true

#      - chat-id: "-1001246502139"
#        title: "Київська ОВА"
#        active: true

      - chat-id: "-1001765605498"
        title: "Чому тривога"
        active: true

      - chat-id: "-1002193251936"
        title: "Чисте небо Київська область та Київ."
        active: true

    ignored-chat-ids:
      - "-1003116942863"

  alert-api:
    base-url: https://api.ukrainealarm.com/api/v3
    api-key: ${UKRAINE_ALARM_API_KEY}
    alarm-region-id: ${ALARM_REGION_ID}
    danger-region-ids: ${DANGER_REGION_IDS}
    polling-delay-ms: 30000

  tdlib:
    api-id: ${TDLIB_API_ID}
    api-hash: ${TDLIB_API_HASH}
    phone-number: ${TDLIB_PHONE_NUMBER}
    database-directory: tdlib-db
    files-directory: tdlib-files
    library-path: ${TDLIB_LIBRARY_PATH}
    auth-code: ${TDLIB_AUTH_CODE:}