app:
  telegram:
    bot-token: ${BOT_TOKEN}
    target-chat-id: ${TARGET_CHANNEL_ID}

  monitor:
    keywords:
      - "біла церква"
      - "бц"
      - "білоцерківський район"
      - "фурси"
      - "узин"
      - "терезине"