app:
  telegram:
    bot-token: "${BOT_TOKEN}"
    target-channel-id: "${TARGET_CHANNEL_ID}"

  monitor:
    keywords:
      - "біла церква"
      - "білу церкву"
      - "білої церкви"
      - "бц"
      - "білоцерківський район"
      - "фурси"
      - "узин"
      - "терезине"

  alert-api:
    base-url: https://api.ukrainealarm.com/api/v3
    api-key: ${UKRAINE_ALARM_API_KEY}
    alarm-region-id: ${ALARM_REGION_ID}
    danger-region-ids: ${DANGER_REGION_IDS}
    polling-delay-ms: 60000

    tdlib:
    api-id: ${TDLIB_API_ID}
    api-hash: ${TDLIB_API_HASH}
    phone-number: ${TDLIB_PHONE_NUMBER}
    database-directory: tdlib-db
    files-directory: tdlib-files