package com.tgbot.shahedmonitorbot.model.admin;

public enum AdminSessionState {

    IDLE,

    WAITING_FOR_NEW_TARGET,
    WAITING_FOR_REMOVE_TARGET,
    WAITING_FOR_NEW_LOCATION,
    WAITING_FOR_REMOVE_LOCATION,

    WAITING_FOR_NEW_DIRECTION,
    WAITING_FOR_REMOVE_DIRECTION,

    WAITING_FOR_NEW_SOURCE_ID,
    WAITING_FOR_NEW_SOURCE_TITLE,
    WAITING_FOR_REMOVE_SOURCE
}